export { createManga } from "./create-manga";
export { deleteManga } from "./delete-manga";
export { getMangaBySlug } from "./get-manga-by-slug";
export { getMangaDetail } from "./get-manga-detail";
export { getMangaList } from "./get-manga-list";
export { getRecentManga } from "./get-recent-manga";
export { getTrendingManga } from "./get-trending-manga";
export { searchManga } from "./search-manga";
export { updateManga } from "./update-manga";
